export const contents = [
  "wedding",
  "marriage",
  "anniversary",
  "gunau choli",
  "meditation class",
  "birthday",
  "bratabandha",
  "birthday",
  "sweet 16",
  "puja",
  "rental services",
  "pasni",
  "other service",
];
